"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _profile_addresses from './profile-addresses.bones.json'
import _admin_session from './admin-session.bones.json'
import _management_resource_page from './management-resource-page.bones.json'

configureBoneyard({"color":"#e7dfd3","animate":"shimmer","shimmerColor":"#f3eee6","speed":"1.8s","transition":180})

registerBones({
  "profile-addresses": _profile_addresses,
  "admin-session": _admin_session,
  "management-resource-page": _management_resource_page,
})
