"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _collection_catalog from './collection-catalog.bones.json'
import _product_detail from './product-detail.bones.json'
import _cart_page from './cart-page.bones.json'
import _favorites_page from './favorites-page.bones.json'
import _search_results from './search-results.bones.json'

configureBoneyard({"color":"#e7dfd3","animate":"shimmer","shimmerColor":"#f3eee6","speed":"1.8s","transition":180})

registerBones({
  "collection-catalog": _collection_catalog,
  "product-detail": _product_detail,
  "cart-page": _cart_page,
  "favorites-page": _favorites_page,
  "search-results": _search_results,
})
