"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _collection_catalog from './collection-catalog.bones.json'
import _product_detail from './product-detail.bones.json'
import _cart_page from './cart-page.bones.json'
import _favorites_page from './favorites-page.bones.json'
import _search_results from './search-results.bones.json'
import _reviews_page from './reviews-page.bones.json'
import _coupons_page from './coupons-page.bones.json'
import _profile_addresses from './profile-addresses.bones.json'
import _profile_orders from './profile-orders.bones.json'
import _profile_favourites from './profile-favourites.bones.json'
import _order_details from './order-details.bones.json'
import _admin_session from './admin-session.bones.json'
import _management_resource_page from './management-resource-page.bones.json'

configureBoneyard({"color":"#e7dfd3","animate":"shimmer","shimmerColor":"#f3eee6","speed":"1.8s","transition":180})

registerBones({
  "collection-catalog": _collection_catalog,
  "product-detail": _product_detail,
  "cart-page": _cart_page,
  "favorites-page": _favorites_page,
  "search-results": _search_results,
  "reviews-page": _reviews_page,
  "coupons-page": _coupons_page,
  "profile-addresses": _profile_addresses,
  "profile-orders": _profile_orders,
  "profile-favourites": _profile_favourites,
  "order-details": _order_details,
  "admin-session": _admin_session,
  "management-resource-page": _management_resource_page,
})
